using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Lib.io.Models;
using Lib.io.Dtos;
using AutoMapper;

namespace Lib.io.Controllers.Api {
    public class BorrowingsController : ApiController {

        private ApplicationDbContext _context;

        public BorrowingsController() {
            _context = new ApplicationDbContext();
        }
        // GET: /api/borrowings
        [HttpGet]
        public IEnumerable<BorrowingDto> GetBorrowings() {

            // Maps the Borrowing to the BorrowingDto, and returns the reference to this method.
            // Eager Load Everything
            return _context.Borrowings
                .Include(b => b.Member)
                .Include(b => b.Member.MembershipType)
                .Include(b => b.Book)
                .Include(b => b.Book.Genre)
                .ToList()
                .Select(Mapper.Map<Borrowing, BorrowingDto>);
        }

        // GET: /api/borrowings/<id>
        [HttpGet]
        public IHttpActionResult GetBorrowings(int id) {
            var borrowing = _context.Borrowings.SingleOrDefault(m => m.Id == id);

            if (borrowing == null)
                return NotFound();
            else
                return Ok(Mapper.Map<Borrowing, NewBorrowingDto>(borrowing));
        }

        // POST: /api/borrowings
        [HttpPost]
        [Authorize(Roles = RoleName.CanManageBorrowings)]
        public IHttpActionResult CreateBorrowing(NewBorrowingDto newBorrowing) {

            if (!ModelState.IsValid)
                return BadRequest();

            var member = _context.Members.Single(m => m.Id == newBorrowing.MemberId);
            var books = _context.Books.Where(b => newBorrowing.BookIds.Contains(b.Id));

            foreach(var book in books) {
                var borrowing = new Borrowing { Member = member, Book = book, DateBorrowed = DateTime.Today };
                _context.Borrowings.Add(borrowing);
            }

            //var borrowing = Mapper.Map<NewBorrowingDto, Borrowing>(borrowingDto);
            _context.SaveChanges();
            // Id is generated by the database, add it to DTO and return it to client.
            //borrowingDto.Id = borrowing.Id;

            // Returns the URI (Unified Resource Identifier)
            return Ok();
        }

        // PUT: /api/borrowings/<id>
        [HttpPut]
        [Authorize(Roles = RoleName.CanManageBorrowings)]
        public void UpdateBorrowing(int id, NewBorrowingDto borrowingDto) {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var borrowingInDb = _context.Borrowings.Single(m => m.Id == id);
            if (borrowingInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            // Use second argument for the existing borrowing in database.
            Mapper.Map<NewBorrowingDto, Borrowing>(borrowingDto, borrowingInDb);

            _context.SaveChanges();
        }

        // DELETE: /apis/borrowings/<id>
        [HttpDelete]
        [Authorize(Roles = RoleName.CanManageBorrowings)]
        public IHttpActionResult DeleteBorrowing(int id) {

            var borrowingInDb = _context.Borrowings.Single(m => m.Id == id);
            if (borrowingInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            _context.Borrowings.Remove(borrowingInDb);
            _context.SaveChanges();

            return Ok();
        }
    }
}
