// <auto-generated />
namespace Lib.io.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddRequiredToBorrowingsDateReturn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRequiredToBorrowingsDateReturn));
        
        string IMigrationMetadata.Id
        {
            get { return "202008230951047_AddRequiredToBorrowingsDateReturn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
